/* Core state: per-session webview token, shared mutable app state and the
   els DOM-reference map. Extracted verbatim from renderer.js. */
/* Per-session token shared with injected webview scripts. Console-message
   markers are only trusted when prefixed with this token, so page JS inside
   WhatsApp Web cannot spoof bridge messages to the host. */
const WADECK_WV_TOKEN = Math.random().toString(36).slice(2) + Math.random().toString(36).slice(2);

/* Encode UTF-8 string to base64 — used by webview inject scripts (insert-text) */
function encodeBase64Utf8(str) {
  const bytes = new TextEncoder().encode(String(str || ''));
  let binary = '';
  for (let i = 0; i < bytes.length; i++) binary += String.fromCharCode(bytes[i]);
  return btoa(binary);
}

const state = {
  accounts: [],
  activeAccountId: null,
  settings: null,
  runtime: null,
  webviews: new Map(),
  panelHidden: true,
  templates: [],
  scheduleRunnerTimer: null,
  attachmentsDraft: [],
  scheduleRunnerBusy: false,
  scheduleTarget: {
    accountId: '',
    accountName: '',
    chatName: '',
  },
  // Single-entry cache: picker only ever shows chats for the active account.
  // Shape: { accountId, at, chats }  (null when nothing fetched yet)
  chatPickerCache: null,
  unreadByAccount: new Map(),
  unreadPollTimer: null,
  dockBadgeTimer: null,
  autoUpdateUnsubscribe: null,
  hostEscapeUnsubscribe: null,
  accountMenuAccountId: '',
  accountMenuDraftIconPath: '',
  accountMenuDraftColor: '',
  draggedAccountId: '',
  crmEditable: false,
  crmTarget: {
    accountId: '',
    accountName: '',
    contactName: '',
    filePath: '',
  },
  startupHubVisible: true,
  startupHubTimeoutId: null,
  weatherGeoCache: new Map(),
  weatherRefreshTimer: null,
  unreadPollBusy: false,
  zoomByAccount: new Map(),
  _hubClockTimer: null,
  hubFilter: 'all', // 'all' | 'unread' | 'favorites' | 'important'
  hubPendingCount: 0,
};

const els = {
  appRoot: document.getElementById('app-root'),
  brandHub: document.getElementById('brand-hub'),
  accountsScrollUp: document.getElementById('accounts-scroll-up'),
  accountsList: document.getElementById('accounts-list'),
  accountsScrollDown: document.getElementById('accounts-scroll-down'),
  addAccount: document.getElementById('add-account'),
  webviews: document.getElementById('webviews'),
  hubScreen: document.getElementById('hub-screen'),
  hubOverlay: document.getElementById('hub-overlay'),
  status: document.getElementById('status'),
  refreshActive: document.getElementById('refresh-active'),
  freezeActive: document.getElementById('freeze-active'),
  openCrmModal: document.getElementById('open-crm-modal'),
  weatherWidget: document.getElementById('weather-widget'),
  weatherToggle: document.getElementById('weather-toggle'),
  weatherIcon: document.getElementById('weather-icon'),
  weatherTemp: document.getElementById('weather-temp'),
  weatherCity: document.getElementById('weather-city'),
  weatherPopover: document.getElementById('weather-popover'),
  weatherCityInput: document.getElementById('weather-city-input'),
  weatherUnit: document.getElementById('weather-unit'),
  weatherRefresh: document.getElementById('weather-refresh'),
  weatherSave: document.getElementById('weather-save'),
  weatherClose: document.getElementById('weather-close'),
  weatherMeta: document.getElementById('weather-meta'),
  activeAccountDisplay: document.getElementById('active-account-display'),
  activeUnread: document.getElementById('active-unread'),
  activeUnreadCount: document.getElementById('active-unread-count'),
  togglePanel: document.getElementById('toggle-panel'),
  panel: document.getElementById('panel'),
  closePanel: document.getElementById('close-panel'),
  manualUpdate: document.getElementById('manual-update'),
  openDataDir: document.getElementById('open-data-dir'),
  themeToggle: document.getElementById('theme-toggle'),
  settingsBack: document.getElementById('settings-back'),
  settingsViewMenu: document.getElementById('settings-view-menu'),
  settingsViewDetail: document.getElementById('settings-view-detail'),
  panelTitleText: document.getElementById('panel-title-text'),
  aboutAppVersion: document.getElementById('about-app-version'),
  aboutElectronVersion: document.getElementById('about-electron-version'),
  aboutChromiumVersion: document.getElementById('about-chromium-version'),
  wsettingsCity: document.getElementById('wsettings-city'),
  wsettingsUnit: document.getElementById('wsettings-unit'),
  wsettingsSave: document.getElementById('wsettings-save'),
  wsettingsRefresh: document.getElementById('wsettings-refresh'),

  saveSettings: document.getElementById('save-settings'),
  settingTranslatorEnabled: document.getElementById('setting-translator-enabled'),
  settingCrmHoverEnabled: document.getElementById('setting-crm-hover-enabled'),
  settingNotificationsEnabled: document.getElementById('setting-notifications-enabled'),
  settingHibernateMinutes: document.getElementById('setting-hibernate-minutes'),
  templateSelect: document.getElementById('template-select'),
  templateTitle: document.getElementById('template-title'),
  templateCategory: document.getElementById('template-category'),
  templateCategoryList: document.getElementById('template-category-list'),
  templateText: document.getElementById('template-text'),
  templateSave: document.getElementById('template-save'),
  templateNew: document.getElementById('template-new'),
  templateDelete: document.getElementById('template-delete'),
  templateToChat: document.getElementById('template-to-chat'),

  scheduleTarget: document.getElementById('schedule-target'),
  openChatPicker: document.getElementById('open-chat-picker'),
  scheduleText: document.getElementById('schedule-text'),
  scheduleAt: document.getElementById('schedule-at'),
  pickAttachments: document.getElementById('pick-attachments'),
  clearAttachments: document.getElementById('clear-attachments'),
  attachmentsList: document.getElementById('attachments-list'),
  createSchedule: document.getElementById('create-schedule'),
  scheduledList: document.getElementById('scheduled-list'),
  chatPickerModal: document.getElementById('chat-picker-modal'),
  closeChatPicker: document.getElementById('close-chat-picker'),
  pickerAccount: document.getElementById('picker-account'),
  pickerChat: document.getElementById('picker-chat'),
  pickerRefresh: document.getElementById('picker-refresh'),
  pickerApply: document.getElementById('picker-apply'),
  accountMenuModal: document.getElementById('account-menu-modal'),
  accountMenuTitle: document.getElementById('account-menu-title'),
  accountMenuName: document.getElementById('account-menu-name'),
  accountMenuSave: document.getElementById('account-menu-save'),
  accountMenuReset: document.getElementById('account-menu-reset'),
  accountMenuIcon: document.getElementById('account-menu-icon'),
  accountMenuResetIcon: document.getElementById('account-menu-reset-icon'),
  accountMenuCancel: document.getElementById('account-menu-cancel'),
  accountMenuChip: document.getElementById('account-menu-chip'),
  accountMenuStatus: document.getElementById('account-menu-status'),
  accountMenuFreeze: document.getElementById('account-menu-freeze'),
  accountMenuPin: document.getElementById('account-menu-pin'),
  accountMenuDelete: document.getElementById('account-menu-delete'),
  sidebarResizeHandle: document.getElementById('sidebar-resize-handle'),

  updateAvailableModal: document.getElementById('update-available-modal'),
  updateVersionText: document.getElementById('update-version-text'),
  updateProgressBar: document.getElementById('update-progress-bar'),
  updateProgressFill: document.getElementById('update-progress-fill'),
  updateStatusText: document.getElementById('update-status-text'),
  updateInstallBtn: document.getElementById('update-install-btn'),
  updateDismissBtn: document.getElementById('update-dismiss-btn'),
  closeUpdateModal: document.getElementById('close-update-modal'),
  updateToast: document.getElementById('update-toast'),
  updateToastTitle: document.getElementById('update-toast-title'),
  updateToastSub: document.getElementById('update-toast-sub'),
  updateToastProgress: document.getElementById('update-toast-progress'),
  updateToastProgressFill: document.getElementById('update-toast-progress-fill'),
  updateToastAction: document.getElementById('update-toast-action'),
  updateToastClose: document.getElementById('update-toast-close'),

  releaseNotesModal: document.getElementById('release-notes-modal'),
  releaseNotesTitle: document.getElementById('release-notes-title'),
  releaseNotesVersion: document.getElementById('release-notes-version'),
  releaseNotesList: document.getElementById('release-notes-list'),
  closeReleaseNotes: document.getElementById('close-release-notes'),

  crmModal: document.getElementById('crm-modal'),
  crmContactName: document.getElementById('crm-contact-name'),
  crmAbout: document.getElementById('crm-about'),
  crmMyInfo: document.getElementById('crm-my-info'),
  crmEdit: document.getElementById('crm-edit'),
  crmSave: document.getElementById('crm-save'),
  crmCopy: document.getElementById('crm-copy'),
  crmClose: document.getElementById('crm-close'),
  crmMeta: document.getElementById('crm-meta'),
  crmAddNote: document.getElementById('crm-add-note'),
  confirmModal: document.getElementById('confirm-modal'),
  confirmTitle: document.getElementById('confirm-title'),
  confirmMessage: document.getElementById('confirm-message'),
  confirmOk: document.getElementById('confirm-ok'),
  confirmCancel: document.getElementById('confirm-cancel'),
  confirmClose: document.getElementById('confirm-close'),

  zoomSlider: document.getElementById('zoom-slider'),
  zoomOut: document.getElementById('zoom-out'),
  zoomIn: document.getElementById('zoom-in'),
  zoomValue: document.getElementById('zoom-value'),

  clocksSettingsList: document.getElementById('clocks-settings-list'),
  clockNewLabel: document.getElementById('clock-new-label'),
  clockNewTz: document.getElementById('clock-new-tz'),
  clockAdd: document.getElementById('clock-add'),
  clockAddForm: document.getElementById('clocks-add-form'),
  clockAddToggle: document.getElementById('clock-add-toggle'),

  toolbarClock: document.getElementById('toolbar-clock'),
  toolbarClockTime: document.getElementById('toolbar-clock-time'),

  openTemplateQuick: document.getElementById('open-template-quick'),
  openScheduleToolbar: document.getElementById('open-schedule-toolbar'),
  sendVoiceMsg: document.getElementById('send-voice-msg'),

  crmFavToggle: document.getElementById('crm-fav-toggle'),
  crmImpToggle: document.getElementById('crm-imp-toggle'),
};

export { WADECK_WV_TOKEN, encodeBase64Utf8, state, els };
