const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('waDeck', {
  bootstrap: () => ipcRenderer.invoke('bootstrap'),
  addAccount: () => ipcRenderer.invoke('add-account'),
  removeAccount: (accountId) => ipcRenderer.invoke('remove-account', accountId),
  renameAccount: (payload) => ipcRenderer.invoke('rename-account', payload),
  setAccountFrozen: (payload) => ipcRenderer.invoke('set-account-frozen', payload),
  saveSettings: (payload) => ipcRenderer.invoke('save-settings', payload),
  translateText: (payload) => ipcRenderer.invoke('translate-text', payload),
  testTranslateApi: (payload) => ipcRenderer.invoke('test-translate-api', payload),
  generateAiReply: (payload) => ipcRenderer.invoke('generate-ai-reply', payload),
  crmLoadContact: (payload) => ipcRenderer.invoke('crm-load-contact', payload),
  crmSaveContact: (payload) => ipcRenderer.invoke('crm-save-contact', payload),
  listAiModels: (payload) => ipcRenderer.invoke('list-ai-models', payload),
  listTemplates: () => ipcRenderer.invoke('list-templates'),
  saveTemplate: (payload) => ipcRenderer.invoke('save-template', payload),
  deleteTemplate: (id) => ipcRenderer.invoke('delete-template', id),
  pickAttachments: () => ipcRenderer.invoke('pick-attachments'),
  scheduleMessage: (payload) => ipcRenderer.invoke('schedule-message', payload),
  listScheduled: (payload) => ipcRenderer.invoke('list-scheduled', payload),
  claimDueScheduled: (payload) => ipcRenderer.invoke('claim-due-scheduled', payload),
  completeScheduled: (payload) => ipcRenderer.invoke('complete-scheduled', payload),
  cancelScheduled: (id) => ipcRenderer.invoke('cancel-scheduled', id),
  openDataDir: () => ipcRenderer.invoke('open-data-dir'),
  getClipboardText: () => ipcRenderer.invoke('get-clipboard-text'),
  setClipboardText: (text) => ipcRenderer.invoke('set-clipboard-text', text),
  setDockBadge: (payload) => ipcRenderer.invoke('set-dock-badge', payload),
});
